import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Button } from "@mui/material";
import { useAuth } from "../store/useAuth";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const { isLogin } = useAuth();
  if (isLogin) {
    router.replace("/profile");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Button
          variant="contained"
          size="large"
          fullWidth
          component={Link}
          href="/login"
          data-test-id="login-navigate"
        >
          Login
        </Button>
      </main>
    </div>
  );
}
